
User.destroy_all
User.create( full_name: "משתמש 1", email: 'a@a.com', password: "12121212")
User.create( full_name: "משתמש 2",email: 'b@b.com', password: "12121212")
User.create( full_name: "משתמש 3",email: 'c@c.com', password: "12121212")
User.create( full_name: "משתמש 4",email: 'd@d.com', password: "12121212")
User.create( full_name: "משתמש 5",email: 'e@e.com', password: "12121212")


Question.destroy_all
Question.create!(title: "שאלה 1", body:"הדבורים (שם מדעי: Apiformes או Anthophila)" , user_id: 1)
Question.create!(title: "שאלה 2", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 1)
Question.create!(title: "שאלה 3 ", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 1)
Question.create!(title: "שאלה 4", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 1)
Question.create!(title: "שאלה 5", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 1)
Question.create!(title: "שאלה 6", body:"הדבורים (שם מדעי: Apiformes או Anthophila)" , user_id: 1)
Question.create!(title: "שאלה 7", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 1)
Question.create!(title: "שאלה 8", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 1)
Question.create!(title: "שאלה 9", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 1)
Question.create!(title: "שאלה 10", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 1)
Question.create!(title: "שאלה 11", body:"הדבורים (שם מדעי: Apiformes או Anthophila)" , user_id: 1)
Question.create!(title: "שאלה 12", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 1)
Question.create!(title: "שאלה 13", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 1)
Question.create!(title: "שאלה 14", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 1)
Question.create!(title: "שאלה 15", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 1)
Question.create!(title: "שאלה 16", body:"הדבורים (שם מדעי: Apiformes או Anthophila)" , user_id: 1)
Question.create!(title: "שאלה 17", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 2)
Question.create!(title: "שאלה 18", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 2)
Question.create!(title: "שאלה 19", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 2)
Question.create!(title: "שאלה 20", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 2)
Question.create!(title: "שאלה 21", body:"הדבורים (שם מדעי: Apiformes או Anthophila)" , user_id: 1)
Question.create!(title: "שאלה 22", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 2)
Question.create!(title: "שאלה 23", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 2)
Question.create!(title: "שאלה 24", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 2)
Question.create!(title: "שאלה 55", body:"הדבורים (שם מדעי: Apiformes או Anthophila) הן קבוצה מונופילטית של חרקים מעופפים, השייכת לעל-המשפחה Apoidea שבסדרת הדבוראים. " , user_id: 2)


Answer.destroy_all
Answer.create!(answer_body: "קיימים כ-20,000 מינים של דבורים, והן נפוצות בכל היבשות, למעט אנטארקטיקה. בישראל קיימים למעלה מאלף מינים של דבורים, שחלק גדול מהם ככל הנראה עדיין לא תואר למדע. ", user_id: 1 , question_id: 2)
Answer.create!(answer_body: "קיימים כ-20,000 מינים של דבורים, והן נפוצות בכל היבשות, למעט אנטארקטיקה. בישראל קיימים למעלה מאלף מינים של דבורים, שחלק גדול מהם ככל הנראה עדיין לא תואר למדע. ", user_id: 1 , question_id: 2)
Answer.create!(answer_body: "קיימים כ-20,000 מינים של דבורים, והן נפוצות בכל היבשות, למעט אנטארקטיקה. בישראל קיימים למעלה מאלף מינים של דבורים, שחלק גדול מהם ככל הנראה עדיין לא תואר למדע. ", user_id: 1 , question_id: 2)
Answer.create!(answer_body: "קיימים כ-20,000 מינים של דבורים, והן נפוצות בכל היבשות, למעט אנטארקטיקה. בישראל קיימים למעלה מאלף מינים של דבורים, שחלק גדול מהם ככל הנראה עדיין לא תואר למדע. ", user_id: 2 , question_id: 3)
Answer.create!(answer_body: "קיימים כ-20,000 מינים של דבורים, והן נפוצות בכל היבשות, למעט אנטארקטיקה. בישראל קיימים למעלה מאלף מינים של דבורים, שחלק גדול מהם ככל הנראה עדיין לא תואר למדע. ", user_id: 2 , question_id: 3)
Answer.create!(answer_body: "קיימים כ-20,000 מינים של דבורים, והן נפוצות בכל היבשות, למעט אנטארקטיקה. בישראל קיימים למעלה מאלף מינים של דבורים, שחלק גדול מהם ככל הנראה עדיין לא תואר למדע. ", user_id: 2 , question_id: 4)
Answer.create!(answer_body: "קיימים כ-20,000 מינים של דבורים, והן נפוצות בכל היבשות, למעט אנטארקטיקה. בישראל קיימים למעלה מאלף מינים של דבורים, שחלק גדול מהם ככל הנראה עדיין לא תואר למדע. ", user_id: 3 , question_id: 4)
Answer.create!(answer_body: "קיימים כ-20,000 מינים של דבורים, והן נפוצות בכל היבשות, למעט אנטארקטיקה. בישראל קיימים למעלה מאלף מינים של דבורים, שחלק גדול מהם ככל הנראה עדיין לא תואר למדע. ", user_id: 3 , question_id: 5)
Answer.create!(answer_body: "קיימים כ-20,000 מינים של דבורים, והן נפוצות בכל היבשות, למעט אנטארקטיקה. בישראל קיימים למעלה מאלף מינים של דבורים, שחלק גדול מהם ככל הנראה עדיין לא תואר למדע. ", user_id: 3 , question_id: 5)
Answer.create!(answer_body: "קיימים כ-20,000 מינים של דבורים, והן נפוצות בכל היבשות, למעט אנטארקטיקה. בישראל קיימים למעלה מאלף מינים של דבורים, שחלק גדול מהם ככל הנראה עדיין לא תואר למדע. ", user_id: 4 , question_id: 2)
Answer.create!(answer_body: "קיימים כ-20,000 מינים של דבורים, והן נפוצות בכל היבשות, למעט אנטארקטיקה. בישראל קיימים למעלה מאלף מינים של דבורים, שחלק גדול מהם ככל הנראה עדיין לא תואר למדע. ", user_id: 4 , question_id: 2)
Answer.create!(answer_body: "קיימים כ-20,000 מינים של דבורים, והן נפוצות בכל היבשות, למעט אנטארקטיקה. בישראל קיימים למעלה מאלף מינים של דבורים, שחלק גדול מהם ככל הנראה עדיין לא תואר למדע. ", user_id: 4 , question_id: 3)
Answer.create!(answer_body: "קיימים כ-20,000 מינים של דבורים, והן נפוצות בכל היבשות, למעט אנטארקטיקה. בישראל קיימים למעלה מאלף מינים של דבורים, שחלק גדול מהם ככל הנראה עדיין לא תואר למדע. ", user_id: 5 , question_id: 4)
Answer.create!(answer_body: "קיימים כ-20,000 מינים של דבורים, והן נפוצות בכל היבשות, למעט אנטארקטיקה. בישראל קיימים למעלה מאלף מינים של דבורים, שחלק גדול מהם ככל הנראה עדיין לא תואר למדע. ", user_id: 5 , question_id: 5)


QuestionComment.destroy_all
QuestionComment.create!(comment_body: "במינים יחידאיים, כל נקבה בונה קן משל עצמה, מאחסנת בו צוף ואבקה שהיא אספה, ומטילה בו את ביציה.", user_id: "1", question_id:"1")
QuestionComment.create!(comment_body: "במינים יחידאיים, כל נקבה בונה קן משל עצמה, מאחסנת בו צוף ואבקה שהיא אספה, ומטילה בו את ביציה.", user_id: "1", question_id:"1")
QuestionComment.create!(comment_body: "במינים יחידאיים, כל נקבה בונה קן משל עצמה, מאחסנת בו צוף ואבקה שהיא אספה, ומטילה בו את ביציה.", user_id: "1", question_id:"1")
QuestionComment.create!(comment_body: "במינים יחידאיים, כל נקבה בונה קן משל עצמה, מאחסנת בו צוף ואבקה שהיא אספה, ומטילה בו את ביציה.", user_id: "1", question_id:"1")
QuestionComment.create!(comment_body: "במינים יחידאיים, כל נקבה בונה קן משל עצמה, מאחסנת בו צוף ואבקה שהיא אספה, ומטילה בו את ביציה.", user_id: "2", question_id:"1")
QuestionComment.create!(comment_body: "במינים יחידאיים, כל נקבה בונה קן משל עצמה, מאחסנת בו צוף ואבקה שהיא אספה, ומטילה בו את ביציה.", user_id: "2", question_id:"2")
QuestionComment.create!(comment_body: "במינים יחידאיים, כל נקבה בונה קן משל עצמה, מאחסנת בו צוף ואבקה שהיא אספה, ומטילה בו את ביציה.", user_id: "2", question_id:"2")
QuestionComment.create!(comment_body: "במינים יחידאיים, כל נקבה בונה קן משל עצמה, מאחסנת בו צוף ואבקה שהיא אספה, ומטילה בו את ביציה.", user_id: "2", question_id:"2")
QuestionComment.create!(comment_body: "במינים יחידאיים, כל נקבה בונה קן משל עצמה, מאחסנת בו צוף ואבקה שהיא אספה, ומטילה בו את ביציה.", user_id: "1", question_id:"3")
QuestionComment.create!(comment_body: "במינים יחידאיים, כל נקבה בונה קן משל עצמה, מאחסנת בו צוף ואבקה שהיא אספה, ומטילה בו את ביציה.", user_id: "1", question_id:"3")
QuestionComment.create!(comment_body: "במינים יחידאיים, כל נקבה בונה קן משל עצמה, מאחסנת בו צוף ואבקה שהיא אספה, ומטילה בו את ביציה.", user_id: "1", question_id:"3")
QuestionComment.create!(comment_body: "במינים יחידאיים, כל נקבה בונה קן משל עצמה, מאחסנת בו צוף ואבקה שהיא אספה, ומטילה בו את ביציה.", user_id: "1", question_id:"4")
QuestionComment.create!(comment_body: "במינים יחידאיים, כל נקבה בונה קן משל עצמה, מאחסנת בו צוף ואבקה שהיא אספה, ומטילה בו את ביציה.", user_id: "1", question_id:"4")

AdminUser.create!(email: 'ben@admin.com', password: 'password', password_confirmation: 'password')